---
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNNER_DEBUG: 1
        with:
          branches: |
            ['+([0-9])?(.{+([0-9]),x}).x', 'master', 'main', 'next', 'next-major', {name: 'beta', prerelease: true}, {name: 'alpha', prerelease: true}]
          extends: |
            @ethima/semantic-release-configuration
          extra_plugins: |
            @ethima/semantic-release-configuration
      - name: Notify JuliaRegistrator of new release
        uses: peter-evans/commit-comment@v3
        if: steps.semantic-release.outputs.new_release_published == 'true'
        with:
          body: '@JuliaRegistrator register branch=${{ steps.semantic-release.outputs.new_release_git_tag }}'
